# Generated by Django 5.0 on 2025-10-19 00:00
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
    ]
